### ISSUE TITLE
Is the Heater always on?

### ISSUE THREAD

**Issue by contrechoc** [arduino-libraries/Arduino_HTS221#14]
The temperature values reading on the BLE Nano Sense with only this sensor working consistently show a temperature 3 to 5 degrees too high (for a room temperature of 16 degrees). 

For example:
Temperature = 22.50 °C
Temperature = 22.42 °C
Temperature = 22.42 °C
Temperature = 22.46 °C
Temperature = 22.44 °C

where other sensors (AHT20, SHT31, MCP9808) and other room thermometers give values around 16 degrees

In the description of the HTS221 the heater is mentioned, but in this GitHub sensor code there is no command to set the heater on or off. 
For instance the temperature sensor SHT31.cpp sensor code shows a way to put the heater on or off, and this gives a temperature difference of 3 degrees also mentioned in the description of this sensor - https://github.com/RobTillaart/Arduino/blob/master/libraries/SHT31/SHT31.cpp

picture of the setting, pro mini with three temperature sensors, and the nano BLE Sense:
![Captura de pantalla 2021-11-28 a las 8 02 31](https://user-images.githubusercontent.com/2486434/143732970-4f2798a0-3c84-4dda-9d1a-50301ef9a96d.jpg)

**Comment by per1234** [comment]
This might explain your results:

https://store.arduino.cc/products/arduino-nano-33-ble-sense#faq

> The HTS221 humidity and temperature sensor: Due to self-heating, when the board is powered by USB, the HTS221 becomes unreliable and shows an offset in each reading that changes with the external temperature. To obtain reliable measurements, the board shall be powered by the 3v3 pin, this could be done by cutting the +3V3 solder jumper on the bottom and powering the board through the VIN pin.

**Comment by contrechoc** [comment]
ok I see, now also here: https://www.arduino.cc/en/Guide/NANO33BLESense, about this warming (so avoid this by cutting 3.3V pad)
then I have to rethink and reconfigure how to get the temp data out most conveniently for my project.
thanks for your speedy reaction!
