### ISSUE TITLE
README.adoc improvement?

### ISSUE THREAD

**Issue by patti-favaron** [arduino-libraries/Arduino_HTS221#21]
The current README.adoc file mentions the Nano 33 BLE Sense. This was true on version 1, but the Version 2 BLE Sense uses a different chip.

The choice by Arduino developed is understandable, as ST Microelectronics has abandoned production of HTS221. However, massive volumes are still present in the market, and use will continue for some time.

Last: there exist implementations of HTS221 accessible to Arduino users (for example the temperature-and-humidity stick by MikroElektronika, or the HTS221 breakouts by AdaFruit and STM itself. At least the AdaFruit's is fully compatible with this library without change needs.

So I propose to drop reference to the Nano 33 BLE sense, with a phrase like

"Allows you to read the temperature and humidity from the ST Microelectronics HTS221 programmable chip"

(or something alike).

If you allow, I can do and push a request.

**Comment by aentinger** [comment]
Fixed by merging #24, thank you for the PR @patti-favaron :bow: !
